### ISSUE TITLE
make error on Raspberry Pi

### ISSUE THREAD

**Issue by panqiincs** [robopeak/rplidar_ros#11]
catkin_make the project on Rasberry Pi(Rasbian OS) will give the following error message:
```
/usr/bin/ld: CMakeFiles/rplidarNode.dir/sdk/src/arch/linux/timer.cpp.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/librt.so.1: error adding symbols: DSO missing from command line
collect2: ld returned 1 exit status
CMakeFiles/rplidarNode.dir/build.make:204: recipe for target 'devel/lib/rplidar_ros/rplidarNode' failed
make[2]: *** [devel/lib/rplidar_ros/rplidarNode] Error 1
CMakeFiles/Makefile2:403: recipe for target 'CMakeFiles/rplidarNode.dir/all' failed
make[1]: *** [CMakeFiles/rplidarNode.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: *** [all] Error 2
```
This problem can be solved by adding a `rt` at the end of `target_link_libraries(rplidarNode ${catkin_LIBRARIES})` in CMakeLists.txt (on line 26).
You can see more details [here](https://www.raspberrypi.org/forums/viewtopic.php?t=19756&p=192119), at the bottom of the post.

**Comment by kintzhao** [comment]
I will close it , if you still have question, please comment, i will reopen it and try to help you.   I can compile correct in Raspberry Pi2 (ubuntu14.04 OS)
