### ISSUE TITLE
Indigo Release

### ISSUE THREAD

**Issue by ipa-mig** [robopeak/rplidar_ros#15]
Hi @robopeak 

Do you plan on releasing this package for ROS Indigo and/or Jade?
We'd like to use this package and it is just more convenient in big setups to have it as a released package.

We'd also like to offer our help for releasing it to Indigo, if you don't plan on doing this.
I'd just want to make sure that we don't get any package conflicts if we release it.

Best regards from Germany
ipa-mig.

**Comment by lakehanne** [comment]
I think it works in indigo. At least I got it to work. Please see my [notes](http://lakehanne.github.io/Robo%20Peak%20Lidar/)

**Comment by ipa-mig** [comment]
Sure it works. But it is not released, i.e. apt-get installable.
Having unreleased packages as a dependency is always cumbersome, as builds fail...

**Comment by ipa-mig** [comment]
PUSH: Could you please provide some information how to proceed.
If I don't get any information, we'll be happy to release this package into Indigo.

We just need to stay in contact about the release procedure.

**Comment by kintzhao** [comment]
thank you the organization of ipa for ever maintaining the indigo version of rplidar_ros.  we have released a new indigo version with sdk 1.5.2 which support rplidar A1 and rplidar A2 .
