### ISSUE TITLE
how to compile and use the driver for Raspberry Pi?

### ISSUE THREAD

**Issue by jabrena** [robopeak/rplidar_ros#18]
Good morning

I used RPLidar with Arduino but now, I would like to use the product using the USB Adapter.
How to use the sensor on a Raspberry Pi?

How to compile and use the SDK?
https://github.com/robopeak/rplidar_ros/tree/master/sdk

Many thanks in advance.

Juan Antonio

**Comment by kintzhao** [comment]
you can follow this : http://www.slamtec.com/cn/Lidar  to use sdk.   if you use it in ROS.   just clone it to your local ros workspace and cmake it.  i have installed it correct at raspberry pi2 (ubuntu14.04) .
