### ISSUE TITLE
/scan message stops publishing

### ISSUE THREAD

**Issue by damanfb** [robopeak/rplidar_ros#20]
I am using the node for a collision avoidance algorithm I'm working on and sometimes while the node is running it stops publishing the /scan message. I am running ```rostopic hz /scan``` and sometimes I get the "no new messages" alert for a long period of time. Sometimes the /scan message comes back, other times I have to power cycle the LIDAR a few times. 

Has anyone seen a similar issue?

**Comment by kintzhao** [comment]
May be you can focus this code ( rplidar_ros/src/node.cpp)  : 
    ros::Publisher scan_pub = nh.advertise<sensor_msgs::LaserScan>("scan", 1000);

you can try change the value of cache .
