### ISSUE TITLE
Port confict 

### ISSUE THREAD

**Issue by polock** [robopeak/rplidar_ros#22]
It seems that turtlebot.minimal.launch uses ttyUSB0 and rplidar.launch uses it too, so I change the port parameter in the rplidar.launch to ttyUSB1 as found with the command of "ls /dev/ttyUSB*"  . But it shows that " Error, cannot bind to the specified serial port ttyUSB1". How can I solve the problem, thank you for your answer!

**Comment by kintzhao** [comment]
You can follow the wiki to remap the serial port.  [How to remap the USB serial port name](https://github.com/robopeak/rplidar_ros/wiki) .  once you plugin the rplidar using USB, the ttyUSB serial port number will add one.  You can check "ls /dev/ttyUSB*" when you only repugin the rplidar.

**Comment by kintzhao** [comment]
you can try to reboot your pc,  and turtlebot  add first , rplidar add next , check "ls /dev/ttyUSB*" .

**Comment by polock** [comment]
Could you explain "install USB port remap: ./scripts/create_udev_rules.sh" in the wiki in detail? I got some trouble in remap.

**Comment by polock** [comment]
Could you explain "install USB port remap: ./scripts/create_udev_rules.sh" in the wiki in detail? I got some trouble in remap.
