### ISSUE TITLE
Repo description and link to ROS wiki page

### ISSUE THREAD

**Issue by bit-pirate** [robopeak/rplidar_ros#28]
Suggesting to add this to this GitHub repo. See our fork for reference: https://github.com/yujinrobot/rplidar_ros

This help ROS users to jump back and forth between the doc (ROS wiki) and code (GitHub repo).

PS: I just created an empty page on the ROS wiki for this package: http://wiki.ros.org/rplidar_ros

**Comment by kintzhao** [comment]
Thanks for your improvement using nodelet,  we will review and evaluate your repo. you should notice that we have  upgrade the SDK  to 1.5.4  for rplidar A1/A2.

**Comment by bit-pirate** [comment]
Hi @kintzhao. This issue is just about adding a description for this repo and a link to a website, e.g. the ROS wiki. I have edited our fork as example:

![rplidar_repo_description_website](https://cloud.githubusercontent.com/assets/1136833/17954265/a783b57c-6ab4-11e6-8cc8-007ca9da4c04.png)

Regarding the code changes in our repo, we will open separate PRs for the new features, such as the nodelet.

**Comment by kintzhao** [comment]
I notice that your node about rplidar_ros  with nodelet has been deleted.
