### ISSUE TITLE
No scanning data received

### ISSUE THREAD

**Issue by sergiosierram** [robopeak/rplidar_ros#35]
I am working with the pioneer lx robot, which has an embedded computer running Ubuntu 12.04, and it has ros hydro installed. I am trying to run rplidar launch file with "roslaunch rplidar_ros rplidar.launch", but I am not getting the Health Status, instead I just get: "Error. unexpected error, code: 800080001"

I tried running the launch file on Ubuntu 14.04 in another computer (with ROS indigo) and I can get the scanning data without problems.

**Comment by kintzhao** [comment]
I ever works well at ubuntu 12.04 hydro with raspberry pi.  I can't  locate your problem through your error message , You can try to check the power of USB if it works at embedded computer .

**Comment by sergiosierram** [comment]
Hi,

First, thanks for your time, answering my issue.
I was checking the power of the USB port, but it seems to be working fine, because the engine is running. Now, I am getting this when I run the launch file.

process[rplidarNode-1]: started with pid [3939]
RPLIDAR running on ROS package rplidar_ros
SDK Version: 1.5.7

And when I run this line: 
$ rostopic echo /scan

I don't get any data

Thanks.
Sergio Sierra

**Comment by kintzhao** [comment]
Do you set the authority of usb:    sudo chmod a+rwx /dev/ttyUSB***

you can test it using linux-driver-test in the [SDK ](http://www.slamtec.com/cn/Lidar)at first.  such as simple_grabber (rplidar_sdk_v1.5.7\sdk\app\simple_grabber)

**Comment by kintzhao** [comment]
Paste the message   :      ls -l /dev/ttyUSB*
the output message :    roslaunch rplidar_ros    rplidar.launch

**Comment by sergiosierram** [comment]
I did set the authority of the usb port, using the udev rules provided in the package. It has all of the permissions and still not working.

**Comment by kintzhao** [comment]
which version of rplidar (A1 / A2)?  I suggest that you support power to the motor of rpliadr by alone  in the embedded computer system.

**Comment by kintzhao** [comment]
Do you solve your problem? I close it, I will reopen it if you still have any question.
