### ISSUE TITLE
operation time out while processing "roslaunch rplidar_ros rolidar.launch"

### ISSUE THREAD

**Issue by didi1745** [robopeak/rplidar_ros#39]
when I input the "ls -l /dev |grep ttyUSB" command, I got "rplidar -> ttyUSB*", but when I am processing "roslaunch rplidar_ros rolidar.launch", I got some problems:

- process[rplidarNode-1]: started with pid [7979]
- RPLIDAR running on ROS package rplidar_ros
- SDK Version: 1.5.7
- Error, operation time out.
- [rplidarNode-1] process has died [pid 7979, exit code 255, cmd /home/ubuntu/turtlebot_ws/devel/lib/rplidar_ros/rplidarNode __name:=rplidarNode __log:=/home/ubuntu/.ros/log/b18a9430-0dd6-11e7-802c-00044b6351e1/rplidarNode-1.log].
- log file: /home/ubuntu/.ros/log/b18a9430-0dd6-11e7-802c-00044b6351e1/rplidarNode-1*.log
- all processes on machine have died, roslaunch will exit
- shutting down processing monitor...
- ... shutting down processing monitor complete
- done
-
BTW,I am using nvidia tx1, rplidar A1,rosdistro:kinetic  :) 
Thank you!

**Comment by kintzhao** [comment]
Does it always occur this problem?
you can test it using linux-driver-test in the [SDK](http://www.slamtec.com/cn/Lidar) at first. such as simple_grabber (rplidar_sdk_v1.5.7\sdk\app\simple_grabber)(not using ROS at first).
 
relevant issue :[issues/37](https://github.com/robopeak/rplidar_ros/issues/37)

**Comment by didi1745** [comment]
- Ultra simple LIDAR data grabber for RPLIDAR.
- Version: 1.5.7
- Error, cannot get device info.

Above is my error info,what should i do now , Is the problem with rplidar and usb?

**Comment by kintzhao** [comment]
firstly, check whether it is work well on PC with windows/linux  by formal SDK test. 
if it is ok, then  check the motor power on your TK1.  if not , contact with[ our support or sales. ](http://www.slamtec.com/cn/Home/About)

**Comment by 3239611294** [comment]
Hello, have you solved your problem? I have the same problem.

**Comment by matianyun** [comment]
you must make sure the type of your lidar,maybe yours is ydlidar,not rplidar
