### ISSUE TITLE
RPLIDAR A2 STL Model

### ISSUE THREAD

**Issue by jabrena** [robopeak/rplidar_ros#45]
Hi,

I would like to know if you have a RPLIDAR A2 STL Model to be used on ROS.

Many thanks in advance.

Juan Antonio

**Comment by kintzhao** [comment]
You can download it from this

https://download.slamtec.com/api/download/rplidar-a2m4-r1-model-3d-stl/1.0?lang=netural

https://www.slamtec.com/cn/Lidar

发件人: Juan Antonio Breña Moral [mailto:notifications@github.com]
发送时间: Wednesday, September 20, 2017 7:21 AM
收件人: robopeak/rplidar_ros
抄送: Subscribed
主题: [robopeak/rplidar_ros] RPLIDAR A2 STL Model (#45)


Hi,

I would like to know if you have a RPLIDAR A2 STL Model to be used on ROS.

**Comment by jabrena** [comment]
Many thanks @kintzhao 
Do you have the STL for RPLIDAR A1 too?

Juan Antonio

**Comment by kintzhao** [comment]
https://www.slamtec.com/cn/Lidar/A1


https://download.slamtec.com/api/download/rplidar-core-a1m8-r1-model-3d-stl/1.0?lang=netural

**Comment by jabrena** [comment]
Many thanks for the support.
