### ISSUE TITLE
Working with BeagleBone Black

### ISSUE THREAD

**Issue by tomek242** [robopeak/rplidar_ros#52]
Hello
I would like to ask how this RPLidar works with BeagleBone Black platform? Could You tell me something about it? Do You have some experience with this platform?
I ask about it because i planned to use this RPLidar in my robot project based on BBB board and Rover 5 Motor Driver Board and  4WD tracked chassis.
Greetings.

**Comment by kintzhao** [comment]
http://www.slamtec.com/cn/Support#rplidar-a2

**Comment by tomek242** [comment]
All right i saw this files and tutorials. Is it necessary to install ROS on the BBB platform before I install the contents of the indicated repository?

**Comment by kintzhao** [comment]
install ROS  at first

**Comment by tomek242** [comment]
Thanks for help kintzhao : )
