### ISSUE TITLE
The map error with gmapping

### ISSUE THREAD

**Issue by kleinHao** [robopeak/rplidar_ros#56]
Hi, when I build map with gmapping and rplidar, there is something wrong. If I move or turn it little by little, it can build the right map as picture 1. However, when I move it fast or turn a large angle in a short time, it doesn't work in a right way. As you can see in picture 2-4, the previous map doesn't move or rotate, so it builds new map incorrectly. I haven't changed the original launch file and don't know why it happens. And I also wanna know, why it says I need to change the static_transform_publisher if I use a real robot in "gmapping.launch" and what I should do. Thanks for your help!
![gmapping1](https://user-images.githubusercontent.com/38314188/38710945-549b0dd0-3ef5-11e8-906a-ab126e741864.png)
![gmapping2](https://user-images.githubusercontent.com/38314188/38710951-5a35e54e-3ef5-11e8-9b42-a0631992ee9a.png)
![gmapping3](https://user-images.githubusercontent.com/38314188/38710952-5a94c42e-3ef5-11e8-988b-21858f3fce8c.png)
![gmapping4](https://user-images.githubusercontent.com/38314188/38710953-5ae5be10-3ef5-11e8-8639-e6d16cd59edb.png)

**Comment by kintzhao** [comment]
check your tf_tree and  frame transform .    http://www.robotics.sei.ecnu.edu.cn/ROS2017/docs/0728/RPLidar%20For%20ROS%20Based%20SLAM_slamtec_KintZhao_2017.pdf
