### ISSUE TITLE
激光启动不起来

### ISSUE THREAD

**Issue by WangGuoFang** [robopeak/rplidar_ros#58]
你好,有些时候你们的激光雷达转不起来,需要人为的转一下才能够启动,而且很多时候就算起来了频率好像减半了.

**Comment by kintzhao** [comment]
is it OK at windows by frame_grabber?   if it has the same problem as your describe, please contact with support@slamtec.com

**Comment by WangGuoFang** [comment]
电脑上面是ok的, 我发现要提供大一点的电流和稳定的电压才能正常工作.
