### ISSUE TITLE
error occured when run command "rosrun rplidar_ros rplidarNode" in virtural box ubuntu 16.04

### ISSUE THREAD

**Issue by HaiCheng16** [robopeak/rplidar_ros#61]
[ INFO] [1527505798.842747574]: RPLIDAR running on ROS package rplidar_ros. SDK Version:1.6.0
[ERROR] [1527505798.843416854]: Error, cannot bind to the specified serial port /dev/ttyUSB0.

**Comment by kintzhao** [comment]
check your port  
ls -l /dev/ttyUSB*
