### ISSUE TITLE
Install RPLidar A1 at +90° with respect to x

### ISSUE THREAD

**Issue by erenaud3** [robopeak/rplidar_ros#63]
Hi !

Is it possible to install the RPLidar A1 differently than with the motor side toward x ? (don't know if I'm clear, sorry...).

I would like to rotate it at 90°, so basically, x and y axis would be inverted if we compare with the wiki example. I need to do that because I don't have enough room otherwise.
I would use it with gmapping.

**Comment by kintzhao** [comment]
you should know more about tf.  modify your tf_tree with right transform
