### ISSUE TITLE
Getting 'Sensitivity' error on launch of rplidar

### ISSUE THREAD

**Issue by thufer2002** [robopeak/rplidar_ros#68]
Will scan find using python package but the /scan message does not function right our of the box? thoughts?

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /rplidarNode/angle_compensate: True
 * /rplidarNode/frame_id: laser
 * /rplidarNode/inverted: False
 * /rplidarNode/serial_baudrate: 115200
 * /rplidarNode/serial_port: /dev/ttyUSB0

NODES
  /
    rplidarNode (rplidar_ros/rplidarNode)

ROS_MASTER_URI=http://192.168.22.66:11311

process[rplidarNode-1]: started with pid [3279]
[ INFO] [1534795160.126721422]: RPLIDAR running on ROS package rplidar_ros. SDK Version:1.7.0
RPLIDAR S/N: 509A9AF0C5E29DD2B6E39DF5D3493116
[ INFO] [1534795160.637768326]: Firmware Ver: 1.24
[ INFO] [1534795160.638347576]: Hardware Rev: 5
[ INFO] [1534795160.641101007]: RPLidar health status : 0
**ERROR] [1534795161.291767343]: scan mode `Sensitivity' is not supported by lidar, supported modes:
[ERROR] [1534795161.292593794]: 	Standard: max_distance: 12.0 m, Point number: 2.0K
[ERROR] [1534795161.293005483]: 	Express: max_distance: 12.0 m, Point number: 4.0K
[ERROR] [1534795161.293501031]: 	Boost: max_distance: 12.0 m, Point number: 8.0K
[ERROR] [1534795161.293875635]: Can not start scan: 80008001!**
^C[rplidarNode-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by kintzhao** [comment]
Only rplidar A3 support  sensitivity mode.
