### ISSUE TITLE
[ERROR] [1535647334.151867876]: Error, cannot bind to the specified serial port /dev/ttyUSB0.

### ISSUE THREAD

**Issue by burakekincioglu** [robopeak/rplidar_ros#69]
i write below command and i get an error as the title.

$ roslaunch rplidar_ros view_rplidar.launch

[ERROR] [1535647334.151867876]: Error, cannot bind to the specified serial port /dev/ttyUSB0.
process[rviz-2]: started with pid [16019]
[rplidarNode-1] process has died [pid 15996, exit code 255, cmd /home/nvidia/racecar-workspace/devel/lib/rplidar_ros/rplidarNode __name:=rplidarNode __log:=/home/nvidia/.ros/log/23793a6c-ac71-11e8-a23d-00044ba50ea0/rplidarNode-1.log].
log file: /home/nvidia/.ros/log/23793a6c-ac71-11e8-a23d-00044ba50ea0/rplidarNode-1*.log

how can i solve this problem

**Comment by burakekincioglu** [comment]
How to remap the USB serial port name
Maybe you should change the usb device port mode with the authority of read and write, more than make the port remap to an fixed name. install USB port remap: ./scripts/create_udev_rules.sh

chaeck the remap use command: ls -l /dev | grep ttyUSB usb_port_remap

Once you have change the USB port remap, you can change the launch file about the serial_port value.
<param name="serial_port" type="string" value="/dev/rplidar"/>


I SOLVED MY PROBLEM WİTH COMANDS THAT ABOVE.

**Comment by kintzhao** [comment]
it has the authority 0777  ./scripts/create_udev_rules.sh

KERNEL=="ttyUSB*", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", MODE:="0777", SYMLINK+="rplidar"
