### ISSUE TITLE
Limit range of scanning angle

### ISSUE THREAD

**Issue by subodh-malgonde** [robopeak/rplidar_ros#71]
I am using RPLidar A1 and I am looking for a way to limit the angular range of the laser scans. I only want to look at data which is right in front of the robot.

I noticed that this is implemented in another repo [kintzhao/rplidar_ros](https://github.com/kintzhao/rplidar_ros/) in the branches [feature/angFilterPublish](https://github.com/kintzhao/rplidar_ros/tree/feature/angFilterPublish) and [feature/fixedAngleFilter](https://github.com/kintzhao/rplidar_ros/tree/feature/fixedAngleFilter). However these branches are 8 commits behind the main repository and I am afraid if I use these branches then I will miss out on the improvements/bug fixes from the later commits.

Any idea how to go about doing this? @kintzhao

**Comment by kintzhao** [comment]
you can find the change code and rebase or cherry-pick it by git..  kintzhao/rplidar_ros  code just for tutorial
