### ISSUE TITLE
Can't rplidar_A1 work without "ros"?

### ISSUE THREAD

**Issue by Odor98** [robopeak/rplidar_ros#73]
it doesn't work?

Arduino is too slow to collect data. ( There is no response to the rplidar_Arduino issue. )

Is there any other way?

**Comment by Odor98** [comment]
I want the same result as roslaunch rplidar_ros rplidarNodeClient.

**Comment by kintzhao** [comment]
you can give more information indetail  about your Arduino  project

**Comment by kintzhao** [comment]
you can get more support without ROS by support@slamtec.com
