### ISSUE TITLE
What is the correct orientation of RPLidar?

### ISSUE THREAD

**Issue by subodh-malgonde** [robopeak/rplidar_ros#77]
I want to install the sensor on my robot such that there is no transform from base_link to laser i.e. no translation and no rotation. Should the tapering end of the sensor be facing the back of my robot, as shown in the picture?

![screen shot 2018-10-24 at 1 43 25 pm](https://user-images.githubusercontent.com/5463437/47416315-10fd4c00-d793-11e8-916d-ca579cc2ddb8.png)

Or should I place it the other way round?

**Comment by GYKrauss** [comment]
The green arrow marked "x" is facing downwards. This means that the motor end is really the "front." If you want to avoid any tf, it must be placed "backwards."

**Comment by kintzhao** [comment]
keep your any install by configure your TF-tree frame:   base_link -> laser

such as: [(13/57)](http://www.robotics.sei.ecnu.edu.cn/ros2016/docs/RPLidar%20For%20ROS%20Based%20SLAM%20and%20Navigation_slamtec_KintZhao.pdf)

**Comment by alrad32** [comment]
Hello, 
Where should the origin of the RPLidar be in the Z-axis? Is it right on the same plane as the laser transmitter and receiver?
