### ISSUE TITLE
RESULT_OPERATION_TIMEOUT on raspberry pi 3 B

### ISSUE THREAD

**Issue by ameykasar** [robopeak/rplidar_ros#78]
I am trying to interface **RPLIDAR A1** with my **Raspberry Pi 3 B 2015** Model running ubuntu 16.04 and ROS kinetic.
I am receiving the following error: `RESULT_OPERATION_TIMEOUT` when I use `roslaunch rplidar_ros rplidar.launch`
I tried using multiple OS images and the standalone SDK but the error persists.
It works fine on my PC running Ubuntu 16.04 and ROS kinetic with same USB cable.
Is this due to Raspberry Pi 3 B only having USB 2.0 ports? Help me find a solution
detailed description of error [here](https://answers.ros.org/question/307109/result_operation_timeout-error-on-raspberry-pi-3-b-when-interfacing-rplidar-a1-with-rplidar_ros-package/)

**Comment by ameykasar** [comment]
@kintzhao

**Comment by ArthurGuy** [comment]
I am experiencing the same problem with the same setup.

**Comment by kintzhao** [comment]
https://github.com/Slamtec/rplidar_ros/issues/1

check your USB-line's power  or your raspberry's power

**Comment by ArthurGuy** [comment]
For me it turned out to be a faulty unit, as soon as it was replaced everything worked as expected.

**Comment by ameykasar** [comment]
> For me it turned out to be a faulty unit, as soon as it was replaced everything worked as expected.

@ArthurGuy  Can you elaborate? By unit do you mean Raspberry Pi or RPLIDAR?
