### ISSUE TITLE
Is it possible to change Angular Resolution in rplidar A3?

### ISSUE THREAD

**Issue by dkoung** [robopeak/rplidar_ros#80]
In the datasheet, it shows 2 different resolution options in the outdoor mode. Where can I set/specify it?

Thanks.

![screenshot from 2018-11-08 09-20-43](https://user-images.githubusercontent.com/23097254/48186266-c570a380-e337-11e8-968d-67b3d93f5a9b.png)

**Comment by kintzhao** [comment]
you can select different scan mode  by the scan_mode
https://github.com/robopeak/rplidar_ros/blob/master/launch/rplidar_a3.launch#L8
https://github.com/robopeak/rplidar_ros/blob/master/src/node.cpp#L243

**Comment by dkoung** [comment]
> you can select different scan mode by the scan_mode
> https://github.com/robopeak/rplidar_ros/blob/master/launch/rplidar_a3.launch#L8
> https://github.com/robopeak/rplidar_ros/blob/master/src/node.cpp#L243

Thanks for your reply.
