### ISSUE TITLE
sudo usage in create_udev_rules.sh and delete_udev_rules.sh

### ISSUE THREAD

**Issue by andersfischernielsen** [robopeak/rplidar_ros#83]
`rplidar_ros/scripts/create_udev_rules.sh` and `rplidar_ros/scripts/delete_udev_rules.sh` fail to run on a ROS container in docker.
`sudo` is unavailable in the docker container (the default user is already super user).

**Comment by kintzhao** [comment]
you can change it by yourself,  try to remove 'sudo'
