### ISSUE TITLE
Rotation problems

### ISSUE THREAD

**Issue by abylikhsanov** [robopeak/rplidar_ros#87]
I have recently bought rplidar A2 and installed that on my differential robot. When I rotate inplace my robot, rplidar messes up the map while mapping and I have to avoid pure rotations. Is that normal?

**Comment by kintzhao** [comment]
you should check your system . TF-tree and your slam

**Comment by abylikhsanov** [comment]
I do not think that this is due to my TF or slam. I have tested the RPLidar without any robot and I can say that lidar cannot cope with normal rotations.
